steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
  # Test: will be later!!!!
  # - name: "gcr.io/cloud-builders/npm"
  #   args: ["run", "test:unit"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy"]
